SELECT ANIMAL_ID
     , NAME
  FROM (SELECT A.ANIMAL_ID  AS ANIMAL_ID
             , A.NAME       AS NAME
             , A.DATETIME   AS OUTS_DATETIME
             , B.DATETIME   AS INS_DATETIME
             , A.DATETIME - B.DATETIME AS DATETIME_DIFF
          FROM ANIMAL_OUTS A
         INNER JOIN ANIMAL_INS B ON (A.ANIMAL_ID = B.ANIMAL_ID)
         ORDER BY DATETIME_DIFF DESC
       )
 WHERE ROWNUM <= 2;
