SELECT TO_CHAR(DATETIME, 'HH24') AS HOUR,
       COUNT(*)
  FROM ANIMAL_OUTS
 GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') BETWEEN '09' AND '19'
 ORDER BY TO_CHAR(DATETIME, 'HH24');
